import request from '../utils/request'

export const login = (data) => request.post('/api/admin/auth/login', data)
export const getProfile = () => request.get('/api/admin/auth/profile')
export const changePassword = (data) => request.put('/api/admin/admins/password', data)

export const getDashboardStats = () => request.get('/api/admin/dashboard/stats')
export const getTodayStats = () => request.get('/api/admin/dashboard/today')
export const getDashboardTrend = (days = 30) => request.get('/api/admin/dashboard/trend', { params: { days } })
export const getAuditStats = () => request.get('/api/admin/dashboard/audit-stats')

export const getUserList = (params) => request.get('/api/admin/users', { params })
export const getUserDetail = (id) => request.get(`/api/admin/users/${id}`)
export const getUserStats = (id) => request.get(`/api/admin/users/${id}/stats`)
export const updateUserStatus = (id, status) => request.put(`/api/admin/users/${id}/status`, { status })

export const getPetList = (params) => request.get('/api/admin/pets', { params })
export const getPetDetail = (id) => request.get(`/api/admin/pets/${id}`)
export const deletePet = (id) => request.delete(`/api/admin/pets/${id}`)

export const getPostList = (params) => request.get('/api/admin/posts', { params })
export const getPostDetail = (id) => request.get(`/api/admin/posts/${id}`)
export const auditPost = (id, data) => request.put(`/api/admin/posts/${id}/audit`, data)
export const deletePost = (id) => request.delete(`/api/admin/posts/${id}`)
export const batchAuditPosts = (data) => request.put('/api/admin/posts/batch-audit', data)
export const getDeletedPosts = (params) => request.get('/api/admin/posts/deleted', { params })
export const restorePost = (id) => request.put(`/api/admin/posts/${id}/restore`)

export const getCommentList = (params) => request.get('/api/admin/comments', { params })
export const deleteComment = (id) => request.delete(`/api/admin/comments/${id}`)
export const restoreComment = (id) => request.put(`/api/admin/comments/${id}/restore`)

export const getReportList = (params) => request.get('/api/admin/reports', { params })
export const handleReport = (id, data) => request.put(`/api/admin/reports/${id}/handle`, data)

export const getNotificationList = (params) => request.get('/api/admin/notifications', { params })
export const sendNotification = (data) => request.post('/api/admin/notifications', data)
export const broadcastNotification = (data) => request.post('/api/admin/notifications/broadcast', data)

export const getFeedbackList = (params) => request.get('/api/admin/feedbacks', { params })
export const getFeedbackDetail = (id) => request.get(`/api/admin/feedbacks/${id}`)
export const replyFeedback = (id, data) => request.put(`/api/admin/feedbacks/${id}/reply`, data)
export const updateFeedbackStatus = (id, status) => request.put(`/api/admin/feedbacks/${id}/status`, { status })
export const deleteFeedback = (id) => request.delete(`/api/admin/feedbacks/${id}`)

export const getAdminList = (params) => request.get('/api/admin/admins', { params })
export const createAdmin = (data) => request.post('/api/admin/admins', data)
export const updateAdmin = (id, data) => request.put(`/api/admin/admins/${id}`, data)
export const updateAdminStatus = (id, status) => request.put(`/api/admin/admins/${id}/status`, { status })
export const resetAdminPassword = (id) => request.put(`/api/admin/admins/${id}/reset-pwd`)

export const getOperationLogs = (params) => request.get('/api/admin/operation-logs', { params })

export const getSettings = () => request.get('/api/admin/settings')
export const updateSettings = (data) => request.put('/api/admin/settings', data)

export const exportUsers = (params) => request.get('/api/admin/export/users', { params, responseType: 'blob' })
export const exportPosts = (params) => request.get('/api/admin/export/posts', { params, responseType: 'blob' })
export const exportReports = (params) => request.get('/api/admin/export/reports', { params, responseType: 'blob' })
export const exportLogs = (params) => request.get('/api/admin/export/logs', { params, responseType: 'blob' })

export const getConfigList = (params) => request.get('/api/admin/config', { params })
export const getConfigCategories = () => request.get('/api/admin/config/categories')
export const createConfig = (data) => request.post('/api/admin/config', data)
export const updateConfig = (id, data) => request.put(`/api/admin/config/${id}`, data)
export const deleteConfig = (id) => request.delete(`/api/admin/config/${id}`)
export const refreshConfigCache = () => request.post('/api/admin/config/refresh-cache')
export const getConfigValue = (key) => request.get(`/api/admin/config/value/${key}`)

export const getAiModelList = () => request.get('/api/admin/ai-models')
export const getAiModelDashboard = () => request.get('/api/admin/ai-models/dashboard')
export const getAiModelDetail = (id) => request.get(`/api/admin/ai-models/${id}`)
export const getAiModelParameters = (id) => request.get(`/api/admin/ai-models/${id}/parameters`)
export const createAiModel = (data) => request.post('/api/admin/ai-models', data)
export const updateAiModel = (id, data) => request.put(`/api/admin/ai-models/${id}`, data)
export const updateAiModelParameters = (id, params) => request.put(`/api/admin/ai-models/${id}/parameters`, params)
export const setAiModelStatus = (id, status) => request.put(`/api/admin/ai-models/${id}/status`, { status })
export const switchAiModel = (data) => request.post('/api/admin/ai-models/switch', data)
export const deleteAiModel = (id) => request.delete(`/api/admin/ai-models/${id}`)
export const getAiModelSwitchLogs = (limit) => request.get('/api/admin/ai-models/switch-logs', { params: { limit } })
export const refreshAiModelCache = () => request.post('/api/admin/ai-models/refresh')
export const getAiModelCacheStats = () => request.get('/api/admin/ai-models/cache/stats')
export const clearAiModelAllCache = () => request.delete('/api/admin/ai-models/cache')
export const clearAiModelPetCache = (petId) => request.delete(`/api/admin/ai-models/cache/pet/${petId}`)
export const getAiModelStats = (id) => request.get(`/api/admin/ai-models/${id}/stats`)
export const getAiModelDailyStats = (id, limit) => request.get(`/api/admin/ai-models/${id}/stats/daily`, { params: { limit } })
export const flushAiModelStats = () => request.post('/api/admin/ai-models/stats/flush')

export const getChallengeList = (params) => request.get('/api/admin/challenges', { params })
export const getChallengeDetail = (id) => request.get(`/api/admin/challenges/${id}`)
export const createChallenge = (data) => request.post('/api/admin/challenges', data)
export const updateChallenge = (id, data) => request.put(`/api/admin/challenges/${id}`, data)
export const deleteChallenge = (id) => request.delete(`/api/admin/challenges/${id}`)
export const updateChallengeStatus = (id, status) => request.put(`/api/admin/challenges/${id}/status`, { status })
export const getChallengeStats = (id) => request.get(`/api/admin/challenges/${id}/stats`)
export const getChallengeParticipants = (id, params) => request.get(`/api/admin/challenges/${id}/participants`, { params })

export const getProductList = (params) => request.get('/api/admin/products', { params })
export const getProductDetail = (id) => request.get(`/api/admin/products/${id}`)
export const createProduct = (data) => request.post('/api/admin/products', data)
export const updateProduct = (id, data) => request.put(`/api/admin/products/${id}`, data)
export const deleteProduct = (id) => request.delete(`/api/admin/products/${id}`)
export const updateProductStatus = (id, status) => request.put(`/api/admin/products/${id}/status`, { status })
export const getProductStats = () => request.get('/api/admin/products/stats')
export const getOrderList = (params) => request.get('/api/admin/products/orders', { params })

export const getClinicList = (params) => request.get('/api/admin/vet-clinics', { params })
export const getClinicDetail = (id) => request.get(`/api/admin/vet-clinics/${id}`)
export const createClinic = (data) => request.post('/api/admin/vet-clinics', data)
export const updateClinic = (id, data) => request.put(`/api/admin/vet-clinics/${id}`, data)
export const deleteClinic = (id) => request.delete(`/api/admin/vet-clinics/${id}`)
export const updateClinicStatus = (id, status) => request.put(`/api/admin/vet-clinics/${id}/status`, { status })
export const setClinicPartner = (id, isPartner) => request.put(`/api/admin/vet-clinics/${id}/partner`, { isPartner })
export const getClinicStats = () => request.get('/api/admin/vet-clinics/stats')
export const getAppointmentList = (params) => request.get('/api/admin/vet-clinics/appointments', { params })
export const updateAppointmentStatus = (id, status) => request.put(`/api/admin/vet-clinics/appointments/${id}/status`, { status })
