import request from '../../utils/request'

export const getAiModelList = () => request.get('/api/admin/ai-models')
export const getAiModelDashboard = () => request.get('/api/admin/ai-models/dashboard')
export const getAiModelDetail = (id) => request.get(`/api/admin/ai-models/${id}`)
export const getAiModelParameters = (id) => request.get(`/api/admin/ai-models/${id}/parameters`)
export const createAiModel = (data) => request.post('/api/admin/ai-models', data)
export const updateAiModel = (id, data) => request.put(`/api/admin/ai-models/${id}`, data)
export const updateAiModelParameters = (id, params) => request.put(`/api/admin/ai-models/${id}/parameters`, params)
export const setAiModelStatus = (id, status) => request.put(`/api/admin/ai-models/${id}/status`, { status })
export const switchAiModel = (data) => request.post('/api/admin/ai-models/switch', data)
export const deleteAiModel = (id) => request.delete(`/api/admin/ai-models/${id}`)
export const getAiModelSwitchLogs = (limit) => request.get('/api/admin/ai-models/switch-logs', { params: { limit } })
export const refreshAiModelCache = () => request.post('/api/admin/ai-models/refresh')
export const getAiModelCacheStats = () => request.get('/api/admin/ai-models/cache/stats')
export const clearAiModelAllCache = () => request.delete('/api/admin/ai-models/cache')
export const clearAiModelPetCache = (petId) => request.delete(`/api/admin/ai-models/cache/pet/${petId}`)
export const getAiModelStats = (id) => request.get(`/api/admin/ai-models/${id}/stats`)
export const getAiModelDailyStats = (id, limit) => request.get(`/api/admin/ai-models/${id}/stats/daily`, { params: { limit } })
export const flushAiModelStats = () => request.post('/api/admin/ai-models/stats/flush')
